# Generated by Django 5.0.1 on 2024-03-15 20:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCuenta',
            fields=[
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=50)),
                ('fecha_creacion_usuario', models.DateTimeField(auto_now_add=True)),
                ('celular', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('documento_identidad', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('numero_cuenta_bancaria', models.CharField(max_length=20, unique=True)),
                ('tipo_cuenta_bancaria', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('fecha_creacion_cuenta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_orden', models.CharField(max_length=50, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('D', 'Deposito')], max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='tasks.usuariocuenta')),
                ('cuenta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='tasks.usuariocuenta')),
            ],
        ),
    ]
